name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Prepare log directory
        run: mkdir -p artifacts

      - name: Install dependencies
        run: npm ci 2>&1 | tee artifacts/npm-ci.log
        shell: bash

      - name: Run lint
        run: npm run lint 2>&1 | tee artifacts/lint.log
        shell: bash

      - name: Run tests
        run: npm test 2>&1 | tee artifacts/test.log
        shell: bash

      - name: Build project
        run: npm run build 2>&1 | tee artifacts/build.log
        shell: bash

      - name: Upload logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: artifacts

  docs:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Verify generated documentation
        run: npm run docs:check 2>&1 | tee docs-check.log
        shell: bash

      - name: Upload docs check logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: docs-check-logs
          path: docs-check.log
