name: Publier le binaire empaquete

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  package:
    name: Construire et publier le binaire Linux
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Installer les dependances
        run: npm ci

      - name: Generer le binaire autonome
        run: npm run package

      - name: Joindre le binaire a la release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/bin/eos-mcp
          asset_name: eos-mcp-linux-x64
          asset_content_type: application/octet-stream
